spring.application.name=Learner_Management_System_live
server.address=0.0.0.0
server.port=1002

spring.datasource.url=jdbc:h2:mem:LMSDB
spring.datasource.username=LMSUser
spring.datasource.password=LMS123
spring.h2.console.enabled=true
spring.datasource.driver-class-name=org.h2.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true